import React from 'react';
import CheckboxTree from 'react-checkbox-tree';
import 'react-checkbox-tree/lib/react-checkbox-tree.css';
import Axios from "axios";
//const nodes = fetch('http://localhost:3000/taxones.json');

function GetKindom(rowtaxon) {
    //rowtaxon = { kingdom: "Plantae", phyllum: "Pteridophyta", class: "Filicopsida", oorder: "Hydropteridales", family: "Salviniaceae", genus: "Salvinia" };
    if (rowtaxon) {
        return rowtaxon.kingdom;
    } else
    {
        return ''
        }
    
}

async function GetJsonTaxones() {

    await Axios({
        url: "http://localhost:3000/taxones.json",
    })
    .then((response) => {
        console.log('RespuestaXXX ', response.data);
        let valores = response.data;
        console.log('valores ', valores);
        console.log('Kingdom ', GetKindom(valores.data[0]));
      //   let ka = '';
      //  const datos = valores.data.map((valores, index) => (
      //     //console.log('tuplas: ', index, GetKindom(index))
      //     console.log(index +" = " + material + " = " + materials[index]));
      //    //  {
      //    //     label: GetKindom(valores, index),
      //    //     value: GetKindom(valores, index)
      //    //  },

      //       // ka = GetKindom( index );
      //   );
        
      //   console.log('datos ', datos);
      //   console.log('JSON.stringify datos ', JSON.stringify(datos));
        // valores = Object.keys(datos).reduce((array, key) => {
        //     return [...array, datos[key]]
        // }, [])

        return ( JSON.stringify(valores.data));
        
    })
    .catch((error) => {
        console.log(error);
        return ([error]);
    });
}

let nodes = GetJsonTaxones();
console.log('nodes ', nodes);
const nodes2 = [
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Chromista",
       "value":"Chromista"
    },
    {
       "label":"Fungi",
       "value":"Fungi"
    },
    {
       "label":"Fungi",
       "value":"Fungi"
    },
    {
       "label":"Fungi",
       "value":"Fungi"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Fungi",
       "value":"Fungi"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Chromista",
       "value":"Chromista"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Chromista",
       "value":"Chromista"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    },
    {
       "label":"Chromista",
       "value":"Chromista"
    },
    {
       "label":"Chromista",
       "value":"Chromista"
    },
    {
       "label":"Chromista",
       "value":"Chromista"
    },
    {
       "label":"Chromista",
       "value":"Chromista"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Animalia",
       "value":"Animalia"
    },
    {
       "label":"Plantae",
       "value":"Plantae"
    }
 ];

class FilterExample extends React.Component {
    state = {
        checked: [
            '/app/Http/Controllers/WelcomeController.js',
            '/app/Http/routes.js',
            '/public/assets/style.css',
            '/public/index.html',
            '/.gitignore',
        ],
        expanded: [
            '/app',
        ],
        filterText: '',
        nodesFiltered: nodes,
        nodes,
    };

    
    
    constructor(props) {
        super(props);

        this.onCheck = this.onCheck.bind(this);
        this.onExpand = this.onExpand.bind(this);
        this.onFilterChange = this.onFilterChange.bind(this);
        this.filterTree = this.filterTree.bind(this);
        this.filterNodes = this.filterNodes.bind(this);
    }

    onCheck(checked) {
        this.setState({ checked });
    }

    onExpand(expanded) {
        this.setState({ expanded });
    }

    onFilterChange(e) {
        this.setState({ filterText: e.target.value }, this.filterTree);
    }

    filterTree() {
        // Reset nodes back to unfiltered state
        if (!this.state.filterText) {
            this.setState((prevState) => ({
                nodesFiltered: prevState.nodes,
            }));

            return;
        }

        const nodesFiltered = (prevState) => (
            { nodesFiltered: prevState.nodes.reduce(this.filterNodes, []) }
        );

        this.setState(nodesFiltered);
    }

    filterNodes(filtered, node) {
        const { filterText } = this.state;
        const children = (node.children || []).reduce(this.filterNodes, []);

        if (
            // Node's label matches the search string
            node.label.toLocaleLowerCase().indexOf(filterText.toLocaleLowerCase()) > -1 ||
            // Or a children has a matching node
            children.length
        ) {
            filtered.push({ ...node, children });
        }

        return filtered;
    }

    render() {
        const {
            checked,
            expanded,
            filterText,
            nodesFiltered,
        } = this.state;

        return (
            
            <div className="filter-container">
                <input
                    className="filter-text"
                    placeholder="Search..."
                    type="text"
                    value={filterText}
                    onChange={this.onFilterChange}
                />
                <CheckboxTree
                    checked={checked}
                    expanded={expanded}
                    iconsClass="fa5"
                    nodes={nodesFiltered}
                    onCheck={this.onCheck}
                    onExpand={this.onExpand}
                />
            </div>
        );
    }
}

export default FilterExample;